# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\delivery\gui\delivery_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deliveryTerminal(object):
    def setupUi(self, deliveryTerminal):
        deliveryTerminal.setObjectName("deliveryTerminal")
        deliveryTerminal.resize(618, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(deliveryTerminal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dishesLayout = QtWidgets.QGridLayout()
        self.dishesLayout.setObjectName("dishesLayout")
        self.verticalLayout.addLayout(self.dishesLayout)
        self.orderTextBrowser = QtWidgets.QTextBrowser(deliveryTerminal)
        self.orderTextBrowser.setObjectName("orderTextBrowser")
        self.verticalLayout.addWidget(self.orderTextBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backToPickButton = QtWidgets.QPushButton(deliveryTerminal)
        self.backToPickButton.setObjectName("backToPickButton")
        self.horizontalLayout_2.addWidget(self.backToPickButton)
        self.doOrderButton = QtWidgets.QPushButton(deliveryTerminal)
        self.doOrderButton.setObjectName("doOrderButton")
        self.horizontalLayout_2.addWidget(self.doOrderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.orderCostLabel = QtWidgets.QLabel(deliveryTerminal)
        self.orderCostLabel.setObjectName("orderCostLabel")
        self.horizontalLayout.addWidget(self.orderCostLabel)
        self.makeOrderButton = QtWidgets.QPushButton(deliveryTerminal)
        self.makeOrderButton.setObjectName("makeOrderButton")
        self.horizontalLayout.addWidget(self.makeOrderButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(deliveryTerminal)
        QtCore.QMetaObject.connectSlotsByName(deliveryTerminal)

    def retranslateUi(self, deliveryTerminal):
        _translate = QtCore.QCoreApplication.translate
        deliveryTerminal.setWindowTitle(_translate("deliveryTerminal", "IKIT Delivery"))
        self.backToPickButton.setText(_translate("deliveryTerminal", "Назад к выбору"))
        self.doOrderButton.setText(_translate("deliveryTerminal", "Все верно, начать готовить"))
        self.orderCostLabel.setText(_translate("deliveryTerminal", "Стоимость:"))
        self.makeOrderButton.setText(_translate("deliveryTerminal", "Заказать"))
