# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\delivery\gui\delivery_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deliveryTerminal(object):
    def setupUi(self, deliveryTerminal):
        deliveryTerminal.setObjectName("deliveryTerminal")
        deliveryTerminal.resize(618, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(deliveryTerminal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dishesLayout = QtWidgets.QGridLayout()
        self.dishesLayout.setObjectName("dishesLayout")
        self.verticalLayout_2.addLayout(self.dishesLayout)
        self.doOredrLayout = QtWidgets.QVBoxLayout()
        self.doOredrLayout.setObjectName("doOredrLayout")
        self.verticalLayout_2.addLayout(self.doOredrLayout)
        self.orderTextBrowser = QtWidgets.QTextBrowser(deliveryTerminal)
        self.orderTextBrowser.setObjectName("orderTextBrowser")
        self.verticalLayout_2.addWidget(self.orderTextBrowser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.doNewOrderLabel = QtWidgets.QLabel(deliveryTerminal)
        self.doNewOrderLabel.setObjectName("doNewOrderLabel")
        self.verticalLayout.addWidget(self.doNewOrderLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doNewOrderButton = QtWidgets.QPushButton(deliveryTerminal)
        self.doNewOrderButton.setObjectName("doNewOrderButton")
        self.horizontalLayout_3.addWidget(self.doNewOrderButton)
        self.exitButton = QtWidgets.QPushButton(deliveryTerminal)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_3.addWidget(self.exitButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.getOrderButton = QtWidgets.QPushButton(deliveryTerminal)
        self.getOrderButton.setObjectName("getOrderButton")
        self.verticalLayout_2.addWidget(self.getOrderButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backToPickButton = QtWidgets.QPushButton(deliveryTerminal)
        self.backToPickButton.setObjectName("backToPickButton")
        self.horizontalLayout_2.addWidget(self.backToPickButton)
        self.doOrderButton = QtWidgets.QPushButton(deliveryTerminal)
        self.doOrderButton.setObjectName("doOrderButton")
        self.horizontalLayout_2.addWidget(self.doOrderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aboutButton = QtWidgets.QPushButton(deliveryTerminal)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout.addWidget(self.aboutButton)
        self.orderCostLabel = QtWidgets.QLabel(deliveryTerminal)
        self.orderCostLabel.setObjectName("orderCostLabel")
        self.horizontalLayout.addWidget(self.orderCostLabel)
        self.makeOrderButton = QtWidgets.QPushButton(deliveryTerminal)
        self.makeOrderButton.setObjectName("makeOrderButton")
        self.horizontalLayout.addWidget(self.makeOrderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(deliveryTerminal)
        QtCore.QMetaObject.connectSlotsByName(deliveryTerminal)

    def retranslateUi(self, deliveryTerminal):
        _translate = QtCore.QCoreApplication.translate
        deliveryTerminal.setWindowTitle(_translate("deliveryTerminal", "IKIT Delivery"))
        self.doNewOrderLabel.setText(_translate("deliveryTerminal", "Заказ успешно выдан, хотите оформить еще один заказ?"))
        self.doNewOrderButton.setText(_translate("deliveryTerminal", "Да!"))
        self.exitButton.setText(_translate("deliveryTerminal", "Нет"))
        self.getOrderButton.setText(_translate("deliveryTerminal", "Забрать заказ"))
        self.backToPickButton.setText(_translate("deliveryTerminal", "Назад к выбору"))
        self.doOrderButton.setText(_translate("deliveryTerminal", "Все верно, начать готовить"))
        self.aboutButton.setText(_translate("deliveryTerminal", "О программе"))
        self.orderCostLabel.setText(_translate("deliveryTerminal", "Стоимость:"))
        self.makeOrderButton.setText(_translate("deliveryTerminal", "Заказать"))
